### ISSUE TITLE
RIP Bijleveld

### ISSUE THREAD

**Issue by dkln** [jvanhees/ruttes-potpourri#3]
https://www.volkskrant.nl/nieuws-achtergrond/minister-bijleveld-stapt-toch-op-haar-positie-werd-binnen-het-cda-onhoudbaar~b6e8e15c/?utm_source=VK&utm_medium=email&utm_campaign=20210917%7Cbreaking&utm_content=Minister%20Bijleveld%20stapt%20toch%20op%20%E2%80%93%20haar%20positie%20werd%20binnen%20het%20CDA%20onhoudbaar&utm_term=184611&ctm_ctid=bb93272a39be39359e3c01df62f4c1a0

**Comment by jvanhees** [comment]
Fixed
